name: App CI
on:
  pull_request:
jobs:
  use-reusable:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      node-version: '18'
      run-tests: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
